version: '3'
services:
  gqlgen:
    image: golang:latest
    volumes:
      - ".:/home"
    working_dir: "/home"
    command: ./entrypoint.sh

  sqlc:
    image: kjconroy/sqlc:latest
    volumes:
      - ".:/src"
    working_dir: "/src"
    command: ["generate"]