version: '3'
services:
  server:
    image: golang:latest
    volumes:
      - ".:/home"
    working_dir: "/home"
    env_file:
      - .env.local
    ports:
      - 8080:8080
    command: ["go", "run", "main.go"]

  postgres:
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgweb:
    image: 'sosedoff/pgweb:latest'
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db?sslmode=disable
    depends_on:
      - postgres
    ports:
      - 8081:8081
    command: ["sh", "-c", "sleep 3; /usr/bin/pgweb --bind=0.0.0.0 --listen=8081"]

  export:
    image: ghcr.io/tk42/graphql-editor:latest
    env_file:
      - .env.local
    volumes:
      - .:/home

volumes:
    postgres_data:
